name: Deploy-React-Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 소스 가져오기
      - name: Checkout Repository
        uses: actions/checkout@v3

      # pnpm 설치
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Node.js 22 설치
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      # npm install
      - name: Install dependencies
        run: pnpm install

      - name: Debug VITE_API_URL
        run: |
          echo "===== DEBUG ENV ====="
          echo "VITE_API_URL=$VITE_API_URL"
          echo "====================="
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # React(Vite) 빌드
      - name: Build project
        run: pnpm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}

      # AWS 인증 (GitHub Secrets 사용)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3 업로드 (build → 버킷 root)
      - name: Deloy to S3
        run: |
          aws s3 sync dist/ s3://petlog-frontend-bucket --delete

      # # CloudFront 캐시 무효화
      # - name: Invalidate CloudFront Cache
      #   run: |
      #     aws cloudfront create-invalidation \
      #       --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} \
      #       --paths "/*"
